[client]
showErrorDetails = true
showDeprecationWarnings = false

[theme]
primaryColor = "#DC2626"
backgroundColor = "#060B14"
secondaryBackgroundColor = "#0D1823"
textColor = "#F8FAFC"
font = "sans serif"
